# Generated by Django 3.1.14 on 2022-11-14 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
