# Generated by Django 3.1.14 on 2022-11-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0014_auto_20221120_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonelementtype',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='element_pictures', verbose_name='изображение'),
        ),
    ]
