# Generated by Django 3.1.14 on 2022-11-20 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0015_pokemonelementtype_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonelementtype',
            name='strong_against',
            field=models.ManyToManyField(blank=True, to='pokemon_entities.PokemonElementType', verbose_name='силён против'),
        ),
    ]
