# Generated by Django 3.1.14 on 2022-11-27 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0016_pokemonelementtype_strong_against'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonelementtype',
            name='img',
            field=models.ImageField(null=True, upload_to='element_pictures', verbose_name='изображение'),
        ),
        migrations.AlterField(
            model_name='pokemonelementtype',
            name='title',
            field=models.CharField(max_length=50, verbose_name='стихия'),
        ),
    ]
