# Generated by Django 3.1.14 on 2022-11-27 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0018_auto_20221127_1406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='element_type',
            new_name='element_types',
        ),
    ]
